"""add organizations and organization scoping

Revision ID: 714a446f6f38
Revises: ca306aad2376
Create Date: 2026-08-13 19:07:00.425063

Phase 3: introduces the tenant boundary. Two new tables (organizations,
organization_memberships) plus a nullable organization_id column on both
roles and user_roles.

No data backfill is needed or performed: NULL on organization_id means
"global" for both roles (a system role usable anywhere) and user_roles (a
role assignment that applies everywhere, independent of any org). Every
row that existed before this migration already satisfies that -- global
was the *only* thing a role or assignment could be pre-Phase-3 -- so every
existing row is already correctly NULL by simply not touching it. This is
also why AuthorizationService's existing (non-org-aware) callers keep
working with zero code changes: passing no organization_id resolves
exactly the same rows they always did.

user_roles' uniqueness moves from a single UNIQUE(user_id, role_id)
constraint to two partial unique indexes (see app/domain/models/
user_role.py's docstring for the full rationale): a plain UNIQUE would let
PostgreSQL's NULL-is-distinct-from-NULL behavior silently allow duplicate
*global* assignments once organization_id exists as a column, which would
regress a guarantee Phase 2.2 already shipped and tested.

reviewed: autogenerated diff was correct including both partial indexes;
manually fixed only the two new foreign key constraints, which
autogenerate created unnamed (`create_foreign_key(None, ...)`) -- an
unnamed constraint has no stable name for downgrade's drop_constraint() to
target, so both are given explicit names here instead.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714a446f6f38'
down_revision: Union[str, None] = 'ca306aad2376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('organization_memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_org_memberships_user_org')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.add_column('roles', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'roles_organization_id_fkey', 'roles', 'organizations',
        ['organization_id'], ['id'], ondelete='CASCADE',
    )
    op.add_column('user_roles', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.create_index('uq_user_roles_user_role_global', 'user_roles', ['user_id', 'role_id'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    op.create_index('uq_user_roles_user_role_org', 'user_roles', ['user_id', 'role_id', 'organization_id'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.create_foreign_key(
        'user_roles_organization_id_fkey', 'user_roles', 'organizations',
        ['organization_id'], ['id'], ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_organization_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_index('uq_user_roles_user_role_org', table_name='user_roles', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index('uq_user_roles_user_role_global', table_name='user_roles', postgresql_where=sa.text('organization_id IS NULL'))
    op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role_id'])
    op.drop_column('user_roles', 'organization_id')
    op.drop_constraint('roles_organization_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'organization_id')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
